---
- name: Create project directories.
  file: path={{ item }} state=directory owner={{ user }} group={{ user }}
  with_items:
    - "{{ project_dir }}"
    - "{{ project_dir }}/config"
    - "{{ project_dir }}/logs"
    - "{{ project_dir }}/webapp"
    - "{{ project_dir }}/venv"

## PostGres
# TODO: Create postgres users.
# TODO: Create postgres database.

# Nginx
- name: Create nginx config.
  template: src=nginx.conf dest={{ project_dir }}/config/nginx.conf
  notify: restart nginx

- name: Link sites-available.
  file: src={{ project_dir }}/config/nginx.conf
        dest=/etc/nginx/sites-available/{{ server_name }}
        state=link
  sudo: yes
  notify: restart nginx

- name: Link sites-enabled.
  file: src=/etc/nginx/sites-available/{{ server_name }}
        dest=/etc/nginx/sites-enabled/{{ server_name }}
        state=link
  sudo: yes
  notify: restart nginx

# Gunicorn
- name: Create gunicorn config.
  template: src=gunicorn.conf dest={{ project_dir }}/config/gunicorn.conf
  notify: restart supervisor

- name: Link gunicorn to supervisor.
  file: src={{ project_dir }}/config/gunicorn.conf
        dest=/etc/supervisor/conf.d/{{server_name}}.conf
        state=link
  sudo: yes

# New Relic
- name: Create newrelic config.
  template: src=newrelic.ini dest={{ project_dir }}/config/newrelic.ini
